In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

Bad key "text.kerning_factor" on line 4 in
C:\Users\Rajit_Sanghvi\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

In [2]:
df = pd.read_csv('UCI_Credit_Card.csv')
df.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,2,2,2,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,2,2,2,34,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,2,2,1,37,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,1,2,1,57,-1,0,-1,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0

In [3]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,29990,29991,29992,29993,29994,29995,29996,29997,29998,29999
ID,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,...,29991.0,29992.0,29993.0,29994.0,29995.0,29996.0,29997.0,29998.0,29999.0,30000.0
LIMIT_BAL,20000.0,120000.0,90000.0,50000.0,50000.0,50000.0,500000.0,100000.0,140000.0,20000.0,...,140000.0,210000.0,10000.0,100000.0,80000.0,220000.0,150000.0,30000.0,80000.0,50000.0
SEX,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
EDUCATION,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,3.0,3.0,...,2.0,2.0,3.0,1.0,2.0,3.0,3.0,2.0,3.0,2.0
MARRIAGE,1.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,...,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0
AGE,24.0,26.0,34.0,37.0,57.0,37.0,29.0,23.0,28.0,35.0,...,41.0,34.0,43.0,38.0,34.0,39.0,43.0,37.0,41.0,46.0
PAY_0,2.0,-1.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,-2.0,...,0.0,3.0,0.0,0.0,2.0,0.0,-1.0,4.0,1.0,0.0
PAY_2,2.0,2.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,-2.0,...,0.0,2.0,0.0,-1.0,2.0,0.0,-1.0,3.0,-1.0,0.0
PAY_3,-1.0,0.0,0.0,0.0,-1.0,0.0,0.0,-1.0,2.0,-2.0,...,0.0,2.0,0.0,-1.0,2.0,0.0,-1.0,2.0,0.0,0.0
PAY_4,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-2.0,...,0.0,2.0,-2.0,0.0,2.0,0.0,-1.0,-1.0,0.0,0.0
PAY_5,-2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,...,0.0,2.0,-2.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0
PAY_6,-2.0,2.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,-1.0,...,0.0,2.0,-2.0,0.0,2.0,0.0,0.0,0.0,-1.0,0.0
BILL_AMT1,3913.0,2682.0,29239.0,46990.0,8617.0,64400.0,367965.0,11876.0,11285.0,0.0,...,138325.0,2500.0,8802.0,3042.0,72557.0,188948.0,1683.0,3565.0,-1645.0,47929.0
BILL_AMT2,3102.0,1725.0,14027.0,48233.0,5670.0,57069.0,412023.0,380.0,14096.0,0.0,...,137142.0,2500.0,10400.0,1427.0,77708.0,192815.0,1828.0,3356.0,78379.0,48905.0
BILL_AMT3,689.0,2682.0,13559.0,49291.0,35835.0,57608.0,445007.0,601.0,12108.0,0.0,...,139110.0,2500.0,0.0,102996.0,79384.0,208365.0,3502.0,2758.0,76304.0,49764.0
BILL_AMT4,0.0,3272.0,14331.0,28314.0,20940.0,19394.0,542653.0,221.0,12211.0,0.0,...,138262.0,2500.0,0.0,70626.0,77519.0,88004.0,8979.0,20878.0,52774.0,36535.0
BILL_AMT5,0.0,3455.0,14948.0,28959.0,19146.0,19619.0,483003.0,-159.0,11793.0,13007.0,...,49675.0,2500.0,0.0,69473.0,82607.0,31237.0,5190.0,20582.0,11855.0,32428.0
BILL_AMT6,0.0,3261.0,15549.0,29547.0,19131.0,20024.0,473944.0,567.0,3719.0,13912.0,...,46121.0,2500.0,0.0,55004.0,81158.0,15980.0,0.0,19357.0,48944.0,15313.0
PAY_AMT1,0.0,0.0,1518.0,2000.0,2000.0,2500.0,55000.0,380.0,3329.0,0.0,...,6000.0,0.0,2000.0,2000.0,7000.0,8500.0,1837.0,0.0,85900.0,2078.0
PAY_AMT2,689.0,1000.0,1500.0,2019.0,36681.0,1815.0,40000.0,601.0,0.0,0.0,...,7000.0,0.0,0.0,111784.0,3500.0,20000.0,3526.0,0.0,3409.0,1800.0
PAY_AMT3,0.0,1000.0,1000.0,1200.0,10000.0,657.0,38000.0,0.0,432.0,0.0,...,4228.0,0.0,0.0,4000.0,0.0,5003.0,8998.0,22000.0,1178.0,1430.0
PAY_AMT4,0.0,1000.0,1000.0,1100.0,9000.0,1000.0,20239.0,581.0,1000.0,13007.0,...,1505.0,0.0,0.0,3000.0,7000.0,3047.0,129.0,4200.0,1926.0,1000.0
PAY_AMT5,0.0,0.0,1000.0,1069.0,689.0,1000.0,13750.0,1687.0,1000.0,1122.0,...,2000.0,0.0,0.0,2000.0,0.0,5000.0,0.0,2000.0,52964.0,1000.0
PAY_AMT6,0.0,2000.0,5000.0,1000.0,679.0,800.0,13770.0,1542.0,1000.0,0.0,...,2000.0,0.0,0.0,2000.0,4000.0,1000.0,0.0,3100.0,1804.0,1000.0
default.payment.next.month,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0

In [5]:
df.dtypes

ID                              int64
LIMIT_BAL                     float64
SEX                             int64
EDUCATION                       int64
MARRIAGE                        int64
AGE                             int64
PAY_0                           int64
PAY_2                           int64
PAY_3                           int64
PAY_4                           int64
PAY_5                           int64
PAY_6                           int64
BILL_AMT1                     float64
BILL_AMT2                     float64
BILL_AMT3                     float64
BILL_AMT4                     float64
BILL_AMT5                     float64
BILL_AMT6                     float64
PAY_AMT1                      float64
PAY_AMT2                      float64
PAY_AMT3                      float64
PAY_AMT4                      float64
PAY_AMT5                      float64
PAY_AMT6                      float64
default.payment.next.month      int64
dtype: object